import type { VariableCatalogEntry } from "../../../types/equationEngine";

export const VARIABLE_CATALOG: VariableCatalogEntry[] = [
  // ── Anthropometrics ──
  {
    slug: "weightKg",
    displayName: "Actual Body Weight",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "heightCm",
    displayName: "Height",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "cm",
    categoryOptions: null,
  },
  {
    slug: "usualBodyWeightKg",
    displayName: "Usual Body Weight",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "dryWeightKg",
    displayName: "Estimated Dry Weight",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "midArmCircumferenceCm",
    displayName: "Mid-Arm Circumference (MAC)",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "cm",
    categoryOptions: null,
  },
  {
    slug: "waistCircumferenceCm",
    displayName: "Waist Circumference",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "cm",
    categoryOptions: null,
  },
  {
    slug: "bodySurfaceAreaM2",
    displayName: "Body Surface Area (BSA)",
    domain: "Anthropometrics",
    dataType: "numeric",
    unit: "m²",
    categoryOptions: null,
  },

  // ── Demographics ──
  {
    slug: "isMale",
    displayName: "Is Male",
    domain: "Demographics",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },
  {
    slug: "isFemale",
    displayName: "Is Female",
    domain: "Demographics",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },

  // ── Derived Metrics ──
  {
    slug: "ageDays",
    displayName: "Age (Days)",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "days",
    categoryOptions: null,
  },
  {
    slug: "ageYears",
    displayName: "Age (Years)",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "years",
    categoryOptions: null,
  },
  {
    slug: "bmi",
    displayName: "Body Mass Index (BMI)",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kg/m²",
    categoryOptions: null,
  },
  {
    slug: "ibwKg",
    displayName: "Ideal Body Weight (IBW)",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "adjustedIbwKg",
    displayName: "Adjusted Ideal Body Weight",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "correctedWeightKg",
    displayName: "Amputation-Corrected Weight",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "msjReeKcal",
    displayName: "Mifflin-St Jeor REE",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kcal/day",
    categoryOptions: null,
  },
  {
    slug: "hbeBmrKcal",
    displayName: "Harris-Benedict BMR",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kcal/day",
    categoryOptions: null,
  },
  {
    slug: "schofieldReeKcal",
    displayName: "Schofield BMR/REE",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kcal/day",
    categoryOptions: null,
  },

  // ── Clinical ──
  {
    slug: "heartRate",
    displayName: "Heart Rate",
    domain: "Clinical",
    dataType: "numeric",
    unit: "bpm",
    categoryOptions: null,
  },
  {
    slug: "oxygenSaturationPct",
    displayName: "Oxygen Saturation (SpO2)",
    domain: "Clinical",
    dataType: "numeric",
    unit: "%",
    categoryOptions: null,
  },
  {
    slug: "temperatureF",
    displayName: "Body Temperature (°F)",
    domain: "Clinical",
    dataType: "numeric",
    unit: "°F",
    categoryOptions: null,
  },
  {
    slug: "maxTemperatureF",
    displayName: "Max Temperature past 24h (°F)",
    domain: "Clinical",
    dataType: "numeric",
    unit: "°F",
    categoryOptions: null,
  },
  {
    slug: "respiratoryRate",
    displayName: "Respiratory Rate",
    domain: "Clinical",
    dataType: "numeric",
    unit: "breaths/min",
    categoryOptions: null,
  },
  {
    slug: "minuteVentilationLMin",
    displayName: "Minute Ventilation (VE)",
    domain: "Clinical",
    dataType: "numeric",
    unit: "L/min",
    categoryOptions: null,
  },
  {
    slug: "fev1Pct",
    displayName: "FEV1 % Predicted",
    domain: "Clinical",
    dataType: "numeric",
    unit: "%",
    categoryOptions: null,
  },
  {
    slug: "tbsaBurnedPct",
    displayName: "Total Body Surface Area Burned",
    domain: "Clinical",
    dataType: "numeric",
    unit: "%",
    categoryOptions: null,
  },
  {
    slug: "gripStrengthKg",
    displayName: "Grip Strength",
    domain: "Clinical",
    dataType: "numeric",
    unit: "kg",
    categoryOptions: null,
  },
  {
    slug: "isMechanicallyVentilated",
    displayName: "Mechanically Ventilated",
    domain: "Clinical",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },

  // ── Clinical Assessments ──
  {
    slug: "ascites",
    displayName: "Ascites Severity",
    domain: "Clinical Assessments",
    dataType: "categorical",
    unit: null,
    categoryOptions: ["None", "Mild", "Moderate", "Severe"],
  },
  {
    slug: "ascitesIsMild",
    displayName: "Ascites is Mild",
    domain: "Clinical Assessments",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },
  {
    slug: "ascitesIsModerate",
    displayName: "Ascites is Moderate",
    domain: "Clinical Assessments",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },
  {
    slug: "ascitesIsSevere",
    displayName: "Ascites is Severe",
    domain: "Clinical Assessments",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },
  {
    slug: "hasPedalEdema",
    displayName: "Has Pedal Edema",
    domain: "Clinical Assessments",
    dataType: "boolean",
    unit: null,
    categoryOptions: null,
  },

  // ── Biochemical ──
  {
    slug: "hemoglobin",
    displayName: "Hemoglobin",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "g/dL",
    categoryOptions: null,
  },
  {
    slug: "hematocrit",
    displayName: "Hematocrit",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "%",
    categoryOptions: null,
  },
  {
    slug: "serumAlbumin",
    displayName: "Serum Albumin",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "g/dL",
    categoryOptions: null,
  },
  {
    slug: "prealbumin",
    displayName: "Prealbumin",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "serumCreatinine",
    displayName: "Serum Creatinine",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "bun",
    displayName: "Blood Urea Nitrogen (BUN)",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "sodium",
    displayName: "Sodium",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mEq/L",
    categoryOptions: null,
  },
  {
    slug: "potassium",
    displayName: "Potassium",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mEq/L",
    categoryOptions: null,
  },
  {
    slug: "chloride",
    displayName: "Chloride",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mEq/L",
    categoryOptions: null,
  },
  {
    slug: "bicarbonate",
    displayName: "Bicarbonate (Total CO2)",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mEq/L",
    categoryOptions: null,
  },
  {
    slug: "phosphorus",
    displayName: "Phosphorus",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "magnesium",
    displayName: "Magnesium",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "calciumTotal",
    displayName: "Calcium (Total)",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "glucose",
    displayName: "Glucose",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "triglycerides",
    displayName: "Triglycerides",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "totalCholesterol",
    displayName: "Total Cholesterol",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "ldlC",
    displayName: "LDL-C",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "hdlC",
    displayName: "HDL-C",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/dL",
    categoryOptions: null,
  },
  {
    slug: "hba1c",
    displayName: "HbA1c",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "%",
    categoryOptions: null,
  },
  {
    slug: "ferritin",
    displayName: "Ferritin",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "ng/mL",
    categoryOptions: null,
  },
  {
    slug: "serumIron",
    displayName: "Serum Iron",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "µg/dL",
    categoryOptions: null,
  },
  {
    slug: "transferrinSaturation",
    displayName: "Transferrin Saturation %",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "%",
    categoryOptions: null,
  },
  {
    slug: "vitaminD",
    displayName: "Vitamin D (25-OH)",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "ng/mL",
    categoryOptions: null,
  },
  {
    slug: "vitaminB12",
    displayName: "Vitamin B12",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "pg/mL",
    categoryOptions: null,
  },
  {
    slug: "zinc",
    displayName: "Zinc",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "µg/dL",
    categoryOptions: null,
  },
  {
    slug: "copper",
    displayName: "Copper",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "µg/dL",
    categoryOptions: null,
  },
  {
    slug: "selenium",
    displayName: "Selenium",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "µg/L",
    categoryOptions: null,
  },
  {
    slug: "crp",
    displayName: "C-Reactive Protein (hs-CRP)",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mg/L",
    categoryOptions: null,
  },
  {
    slug: "tsh",
    displayName: "TSH",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mIU/L",
    categoryOptions: null,
  },
  {
    slug: "lactate",
    displayName: "Lactate",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "mmol/L",
    categoryOptions: null,
  },
  {
    slug: "lipase",
    displayName: "Serum Lipase",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "U/L",
    categoryOptions: null,
  },
  {
    slug: "amylase",
    displayName: "Serum Amylase",
    domain: "Biochemical",
    dataType: "numeric",
    unit: "U/L",
    categoryOptions: null,
  },

  // ── Condition-specific inputs ──
  {
    slug: "postBurnDay",
    displayName: "Post-Burn Day",
    domain: "Clinical",
    dataType: "numeric",
    unit: "days",
    categoryOptions: null,
  },
  {
    slug: "coreTempC",
    displayName: "Core Temperature (°C)",
    domain: "Clinical",
    dataType: "numeric",
    unit: "°C",
    categoryOptions: null,
  },
  {
    slug: "currentKcalIntake",
    displayName: "Current Caloric Intake",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kcal/day",
    categoryOptions: null,
  },
  {
    slug: "icMeasuredKcal",
    displayName: "Measured REE (Indirect Calorimetry)",
    domain: "Derived Metrics",
    dataType: "numeric",
    unit: "kcal/day",
    categoryOptions: null,
  },
  {
    slug: "icCaf",
    displayName: "Indirect Calorimetry Activity Factor",
    domain: "Clinical",
    dataType: "numeric",
    unit: null,
    categoryOptions: null,
  },
  {
    slug: "coefficientOfFatAbsorption",
    displayName: "Coefficient of Fat Absorption",
    domain: "Clinical",
    dataType: "numeric",
    unit: "0–1",
    categoryOptions: null,
  },
  {
    slug: "urineOutputMlDay",
    displayName: "Urine Output",
    domain: "Clinical",
    dataType: "numeric",
    unit: "mL/day",
    categoryOptions: null,
  },
  {
    slug: "exudateVolumeL",
    displayName: "Exudate Volume",
    domain: "Clinical",
    dataType: "numeric",
    unit: "L/day",
    categoryOptions: null,
  },
  {
    slug: "palValue",
    displayName: "Physical Activity Level (PAL)",
    domain: "Clinical",
    dataType: "numeric",
    unit: null,
    categoryOptions: null,
  },
];
