export const MASTER_DOMAINS = [
  {
    id: "patient",
    title: "Patient Identity",
    fields: [
      { key: "first_name", label: "First Name", locked: true },
      { key: "last_name",  label: "Last Name", locked: true },
      { key: "dob",        label: "Date of Birth", locked: true },
      { key: "mrn",        label: "Medical Record Number (MRN)" },
      { key: "note_date",  label: "Note Date", locked: true },
      { key: "admission_date", label: "Admission Date" },
      { key: "sex", label: "Sex" },
      { key: "languages", label: "Preferred Languages" },
    ]
  },
  {
    id: "patientHistory",
    title: "PH. Patient History",
    fields: [
      { key: "purposeOfVisit", label: "Purpose of Visit" },
      { key: "chiefComplaint", label: "Chief Complaint" },
      { key: "medHx",          label: "Medical History" },
      { key: "familyHx",       label: "Family History" },
      { key: "socialHx",       label: "Social History" },
    ]
  },
  {
    id: "anthro",
    title: "A. Anthropometrics",
    fields: [
      { key: "ht", label: "Height" },
      { key: "wt", label: "Weight" },
      { key: "ubw", label: "Usual Body Weight" },
      { key: "ubwDate", label: "UBW Date" },
      { key: "waist", label: "Waist Circumference" },
      { key: "mac", label: "Mid-Arm Circumference" },
      { key: "calf", label: "Calf Circumference" },
      { key: "head", label: "Head Circumference" },
      { key: "triceps", label: "Skinfold: Triceps" },
      { key: "subscapular", label: "Skinfold: Subscapular" },
      { key: "suprailiac", label: "Skinfold: Suprailiac" },
      { key: "thigh", label: "Skinfold: Thigh" },
      { key: "edw",              label: "Estimated Dry Weight" },
      { key: "isFluidShift",     label: "Fluid Shift Flag" },
      { key: "amputations",      label: "Amputation Selections" },
      { key: "ampSegments",      label: "Amputation Segment Data (Rich)" },
      { key: "circUnit",         label: "Circumference Unit" },
      { key: "past_ht",          label: "Past Height (Growth Velocity)" },
      { key: "past_wt",          label: "Past Weight (Growth Velocity)" },
      { key: "past_head",        label: "Past Head Circumference" },
      { key: "past_htDate",      label: "Past Height Date" },
      { key: "past_wtDate",      label: "Past Weight Date" },
      { key: "past_headDate",    label: "Past Head Circumference Date" },
      { key: "dexaScans",        label: "DEXA Scan Records" },
    ]
  },
  {
    id: "biochemical",
    title: "B. Biochemical Data",
    fields: [
      { key: "activeLabKeys",   label: "Active Lab Panel (dynamic)" },
      { key: "userPresets",     label: "Saved Lab Presets" },
    ]
  },
  {
    id: "clinical",
    title: "C. Clinical & NFPE",
    fields: [
      { key: "allergiesIntolerances", label: "Allergies & Intolerances" },
      { key: "medicalDevices", label: "Medical Devices" },
      { key: "medications", label: "Medications" },
      { key: "temples", label: "NFPE: Temples" },
      { key: "clavicles", label: "NFPE: Clavicles" },
      { key: "shoulders", label: "NFPE: Shoulders" },
      { key: "scapula", label: "NFPE: Scapula" },
      { key: "interosseous", label: "NFPE: Interosseous" },
      { key: "thighs", label: "NFPE: Thighs" },
      { key: "calves", label: "NFPE: Calves" },
      { key: "orbital", label: "NFPE: Orbital Fat" },
      { key: "cheek", label: "NFPE: Cheek Fat" },
      { key: "tricepsFat", label: "NFPE: Triceps Fat" },
      { key: "midAxillary", label: "NFPE: Mid-Axillary" },
      { key: "pittingEdema", label: "NFPE: Pitting Edema" },
      { key: "pedalEdema", label: "NFPE: Pedal Edema" },
      { key: "ascites", label: "NFPE: Ascites" },
      { key: "temp", label: "Vital: Temperature" },
      { key: "hr", label: "Vital: Heart Rate" },
      { key: "spo2", label: "Vital: SpO2" },
      { key: "bp", label: "Vital: Blood Pressure" },
      { key: "rr", label: "Vital: Resp Rate" },
      { key: "gripStrength", label: "Grip Strength" },
      { key: "giDistress", label: "GI Distress" },
      { key: "giSymptoms", label: "GI Symptoms (Checklist)" },
      { key: "stoolType", label: "Stool Type" },
      { key: "dentition", label: "Dentition" },
      { key: "swallowChewConcerns", label: "Swallow/Chew Concerns" },
      { key: "nicheConditionFlags", label: "Specialized Population Flags" },
      { key: "imaging_smi", label: "Imaging: SMI" },
      { key: "tempMax", label: "Vital: Max Temp past 24h" },
      { key: "ve", label: "Vital: Minute Ventilation (Ve)" },
      { key: "fev1", label: "FEV1 % Predicted" },
      { key: "tbsa", label: "TBSA Burned (%)" },
      { key: "clinicalNotes", label: "General Clinical Notes" },
      { key: "screenings",              label: "Clinical Screenings" },
      { key: "oralHygiene",             label: "Oral Hygiene" },
      { key: "edemaDescription",        label: "Edema Description" },
      { key: "hair",                    label: "NFPE Micronutrient: Hair" },
      { key: "eyes",                    label: "NFPE Micronutrient: Eyes" },
      { key: "mouthLips",               label: "NFPE Micronutrient: Mouth & Lips" },
      { key: "tongue",                  label: "NFPE Micronutrient: Tongue" },
      { key: "teethGums",               label: "NFPE Micronutrient: Teeth & Gums" },
      { key: "headNeck",                label: "NFPE Micronutrient: Head & Neck" },
      { key: "nails",                   label: "NFPE Micronutrient: Nails" },
      { key: "skin",                    label: "NFPE Micronutrient: Skin" },
      { key: "imaging_muscleAttenuation", label: "Imaging: Muscle Attenuation (HU)" },
      { key: "imaging_imat",            label: "Imaging: IMAT" },
      { key: "imaging_vat",             label: "Imaging: VAT (cm²)" },
      { key: "imaging_notes",           label: "Imaging: Notes" },
    ]
  },
  {
    id: "dietary",
    title: "D. Dietary Data",
    fields: [
      { key: "dietOrder", label: "Current Rx Diet Order" },
      { key: "oralCalories", label: "Oral Calories" },
      { key: "oralProtein", label: "Oral Protein" },
      { key: "oralWater", label: "Oral Water" },
      { key: "fluidIntake", label: "Total Fluid Intake" },
      { key: "mealPatterns", label: "Meal Patterns" },
      { key: "eeiPercent", label: "Estimated Intake (%)" },
      { key: "eeiTimeframe", label: "Intake Timeframe" },
      { key: "herbalCAM", label: "Herbal/CAM" },
      { key: "supplements", label: "Supplements" },
      { key: "understanding", label: "Nutrition Understanding" },
      { key: "readiness", label: "Readiness for Change" },
      { key: "foodSecurity", label: "Food Security" },
      { key: "physicalLevel", label: "Physical Activity Level" },
      { key: "adls", label: "ADLs" },
      { key: "recall",           label: "24-Hour Dietary Recall" },
      { key: "currentDiets",     label: "Current Diet Type" },
      { key: "feedingTasks",     label: "Feeding Tasks" },
      { key: "psychTies",        label: "Psychological Food Ties" },
      { key: "mealPrep",         label: "Meal Preparation" },
      { key: "eatingOut",        label: "Eating Out Frequency" },
      { key: "bingePurge",       label: "Binge/Purge Behaviors" },
      { key: "foodSupplies",     label: "Food Supplies" },
      { key: "transport",        label: "Food Access: Transportation" },
      { key: "culturalReligious", label: "Cultural & Religious Food Practices" },
      { key: "socialDynamics",   label: "Social Dynamics" },
      { key: "eatingEnv",        label: "Eating Environment" },
      { key: "perception",       label: "Patient Food Perception" },
      { key: "qolGoals",         label: "Quality of Life Goals" },
      { key: "ivOrders",         label: "IV Orders" },
      { key: "enState",          label: "Enteral Nutrition Orders" },
      { key: "pnState",          label: "Parenteral Nutrition Orders" },
    ]
  },
  {
    id: "diagnosis",
    title: "Dx. Nutrition Diagnosis",
    fields: [
      { key: "diagnosis", label: "Nutrition Diagnosis (P)" },
      { key: "etiology", label: "Primary Etiology (E)" },
      { key: "signsSymptoms", label: "Primary Signs/Symptoms (S)" },
      { key: "nutritionDxNarrative", label: "Diagnostic Narrative" },
      { key: "priorityRanking", label: "Priority Ranking" },
      { key: "additionalDiagnoses", label: "Additional PES Statements" },
    ]
  },
  {
    id: "intervention",
    title: "I. Intervention",
    fields: [
      { key: "nd_mealsSnacks", label: "ND: Meals & Snacks" },
      { key: "nd_supplementalFeeding", label: "ND: Enteral/Parenteral" },
      { key: "ed_purpose", label: "Education Purpose" },
      { key: "c_theory", label: "Counseling Theory" },
      { key: "cc_followUpPlan", label: "Follow-up Plan" },
      { key: "goalStatement", label: "Goal Statement" },
      { key: "interventionNotes", label: "Intervention Notes" },
      { key: "npActiveModes",            label: "Active Nutrition Support Modes" },
      { key: "npOral_energyKcal",        label: "NP Oral: Energy (kcal)" },
      { key: "npOral_textureModification", label: "NP Oral: Texture Modification" },
      { key: "npOral_oralSupplements",   label: "NP Oral: Oral Supplements" },
      { key: "npOral_isNpo",             label: "NP Oral: NPO Status" },
      { key: "npEnteral_formulaName",    label: "NP Enteral: Formula Name" },
      { key: "npEnteral_adminMethod",    label: "NP Enteral: Admin Method" },
      { key: "npEnteral_kcalLow",        label: "NP Enteral: Kcal Target (Low)" },
      { key: "npEnteral_kcalHigh",       label: "NP Enteral: Kcal Target (High)" },
      { key: "npParenteral_energyKcal",  label: "NP Parenteral: Energy (kcal)" },
      { key: "npParenteral_solutionType", label: "NP Parenteral: Solution Type" },
      { key: "npIvFluid_solution",       label: "NP IV Fluid: Solution" },
      { key: "ndImplementation",         label: "ND/E/C/RC Implementation Tree" },
      { key: "goalTimeframe",            label: "Goal Timeframe" },
      { key: "goalMeasurable",           label: "Measurable Goal Outcome" },
    ]
  },
  {
    id: "monitorEval",
    title: "ME. Monitor & Evaluate",
    fields: [
      { key: "monitorFrequency", label: "Monitor Frequency" },
      { key: "monitoredBy", label: "Monitored By" },
      { key: "outcome_progress", label: "Outcome Progress" },
      { key: "dischargeRecs", label: "Discharge Recommendations" },
      { key: "meNotes", label: "ME Notes" },
      { key: "monitoredIndicators",   label: "Monitored Indicators" },
      { key: "criteria_anthropo",     label: "Anthropometric Targets" },
      { key: "criteria_labs",         label: "Biochemical Targets" },
      { key: "criteria_dietary",      label: "Dietary/Intake Targets" },
      { key: "criteria_clinical",     label: "Clinical/Functional Targets" },
      { key: "criteria_functional",   label: "Functional Outcome Targets" },
      { key: "outcome_nextSteps",     label: "Next Steps / Plan Adjustments" },
      { key: "transitionPlan",        label: "Transition / Follow-Up Plan" },
    ]
  },
  {
    id: "standards",
    title: "S. Comparative Standards",
    fields: [
      { key: "condition",      label: "Clinical Condition Selected" },
      { key: "variant",        label: "Condition Sub-type / Variant" },
      { key: "icKcal",         label: "Indirect Calorimetry mREE (kcal)" },
      { key: "snapshot",       label: "Evaluation Snapshot (Engine Output)" },
    ]
  },
  {
    id: "refeeding",
    title: "RF. Refeeding Screen",
    fields: [
      { key: "c1_manualRisk",    label: "C1: BMI Risk Override" },
      { key: "c2_source",        label: "C2: Weight Loss Source" },
      { key: "c2_manualPct",     label: "C2: Manual Weight Loss (%)" },
      { key: "c3_option",        label: "C3: Energy Intake Option" },
      { key: "c3_intakePct",     label: "C3: Energy Intake (%)" },
      { key: "c4_electrolytes",  label: "C4: Electrolyte Criteria" },
      { key: "c7_selected",      label: "C7: Comorbidities Selected" },
      { key: "screenNotes",      label: "Refeeding Screen Notes" },
      { key: "screenedAt",       label: "Screen Timestamp" },
    ]
  }
];