export const MASTER_DOMAINS = [
  {
    id: "patient",
    title: "Patient Identity",
    fields: [
      { key: "first_name", label: "First Name", locked: true },
      { key: "last_name",  label: "Last Name", locked: true },
      { key: "dob",        label: "Date of Birth", locked: true },
      { key: "mrn",        label: "Medical Record Number (MRN)" },
      { key: "note_date",  label: "Note Date", locked: true },
      { key: "admission_date", label: "Admission Date" },
      { key: "sex", label: "Sex" },
      { key: "languages", label: "Preferred Languages" },
    ]
  },
  {
    id: "anthro",
    title: "A. Anthropometrics",
    fields: [
      { key: "ht", label: "Height" },
      { key: "wt", label: "Weight" },
      { key: "ubw", label: "Usual Body Weight" },
      { key: "ubwDate", label: "UBW Date" },
      { key: "waist", label: "Waist Circumference" },
      { key: "mac", label: "Mid-Arm Circumference" },
      { key: "calf", label: "Calf Circumference" },
      { key: "head", label: "Head Circumference" },
      { key: "triceps", label: "Skinfold: Triceps" },
      { key: "subscapular", label: "Skinfold: Subscapular" },
      { key: "suprailiac", label: "Skinfold: Suprailiac" },
      { key: "thigh", label: "Skinfold: Thigh" },
    ]
  },
  {
    id: "clinical",
    title: "C. Clinical & NFPE",
    fields: [
      { key: "chiefComplaint", label: "Chief Complaint" },
      { key: "medHx", label: "Medical History" },
      { key: "familyHx", label: "Family History" },
      { key: "socialHx", label: "Social History" },
      { key: "allergiesIntolerances", label: "Allergies & Intolerances" },
      { key: "medicalDevices", label: "Medical Devices" },
      { key: "medications", label: "Medications" },
      { key: "temples", label: "NFPE: Temples" },
      { key: "clavicles", label: "NFPE: Clavicles" },
      { key: "shoulders", label: "NFPE: Shoulders" },
      { key: "scapula", label: "NFPE: Scapula" },
      { key: "interosseous", label: "NFPE: Interosseous" },
      { key: "thighs", label: "NFPE: Thighs" },
      { key: "calves", label: "NFPE: Calves" },
      { key: "orbital", label: "NFPE: Orbital Fat" },
      { key: "cheek", label: "NFPE: Cheek Fat" },
      { key: "tricepsFat", label: "NFPE: Triceps Fat" },
      { key: "midAxillary", label: "NFPE: Mid-Axillary" },
      { key: "pittingEdema", label: "NFPE: Pitting Edema" },
      { key: "pedalEdema", label: "NFPE: Pedal Edema" },
      { key: "ascites", label: "NFPE: Ascites" },
      { key: "temp", label: "Vital: Temperature" },
      { key: "hr", label: "Vital: Heart Rate" },
      { key: "spo2", label: "Vital: SpO2" },
      { key: "bp", label: "Vital: Blood Pressure" },
      { key: "rr", label: "Vital: Resp Rate" },
      { key: "gripStrength", label: "Grip Strength" },
      { key: "giDistress", label: "GI Distress" },
      { key: "chewing", label: "Chewing Ability" },
      { key: "swallowing", label: "Swallowing Ability" },
      { key: "imaging_smi", label: "Imaging: SMI" },
      { key: "tempMax", label: "Vital: Max Temp past 24h" },
      { key: "ve", label: "Vital: Minute Ventilation (Ve)" },
      { key: "fev1", label: "FEV1 % Predicted" },
      { key: "tbsa", label: "TBSA Burned (%)" },
      { key: "clinicalNotes", label: "General Clinical Notes" },
    ]
  },
  {
    id: "dietary",
    title: "D. Dietary Data",
    fields: [
      { key: "dietOrder", label: "Current Rx Diet Order" },
      { key: "oralCalories", label: "Oral Calories" },
      { key: "oralProtein", label: "Oral Protein" },
      { key: "oralWater", label: "Oral Water" },
      { key: "fluidIntake", label: "Total Fluid Intake" },
      { key: "mealPatterns", label: "Meal Patterns" },
      { key: "eeiPercent", label: "Estimated Intake (%)" },
      { key: "eeiTimeframe", label: "Intake Timeframe" },
      { key: "herbalCAM", label: "Herbal/CAM" },
      { key: "supplements", label: "Supplements" },
      { key: "understanding", label: "Nutrition Understanding" },
      { key: "readiness", label: "Readiness for Change" },
      { key: "foodSecurity", label: "Food Security" },
      { key: "physicalLevel", label: "Physical Activity Level" },
      { key: "adls", label: "ADLs" },
    ]
  },
  {
    id: "diagnosis",
    title: "Dx. Nutrition Diagnosis",
    fields: [
      { key: "diagnosis", label: "Primary Problem (P)" },
      { key: "etiology", label: "Primary Etiology (E)" },
      { key: "signsSymptoms", label: "Primary Signs/Symptoms (S)" },
      { key: "nutritionDxNarrative", label: "Diagnostic Narrative" },
      { key: "priorityRanking", label: "Priority Ranking" },
    ]
  },
  {
    id: "intervention",
    title: "I. Intervention",
    fields: [
      { key: "nd_mealsSnacks", label: "ND: Meals & Snacks" },
      { key: "nd_supplementalFeeding", label: "ND: Enteral/Parenteral" },
      { key: "ed_purpose", label: "Education Purpose" },
      { key: "c_theory", label: "Counseling Theory" },
      { key: "cc_followUpPlan", label: "Follow-up Plan" },
      { key: "goalStatement", label: "Goal Statement" },
      { key: "interventionNotes", label: "Intervention Notes" },
    ]
  },
  {
    id: "monitorEval",
    title: "ME. Monitor & Evaluate",
    fields: [
      { key: "monitorFrequency", label: "Monitor Frequency" },
      { key: "monitoredBy", label: "Monitored By" },
      { key: "outcome_progress", label: "Outcome Progress" },
      { key: "dischargeRecs", label: "Discharge Recommendations" },
      { key: "meNotes", label: "ME Notes" },
    ]
  }
];