// src/entities/note/defaults.ts

export const defaultPatientData = {
  lastName: "",
  firstName: "",
  dob: "",
  sex: "",
  mrn: "",
  admissionDate: new Date().toISOString().split("T")[0],
  noteDate: new Date().toISOString().split("T")[0],
  languages: "",
};

export const defaultAnthro = {
  ht: "",
  htUnit: "cm",
  wt: "",
  wtUnit: "kg",
  ubw: "",
  ubwTime_amount1: "",
  ubwTime_unit1: "mo",
  ubwTime_amount2: "",
  ubwTime_unit2: "mo",
  waist: "",
  mac: "",
  calf: "",
  head: "",
  circUnit: "cm",
  triceps: "",
  subscapular: "",
  suprailiac: "",
  thigh: "",
  skinfoldUnit: "mm",
  past_ht: "",
  past_htUnit: "cm",
  past_wt: "",
  past_wtUnit: "kg",
  past_head: "",
  past_headUnit: "cm",
  past_htDate: "",
  past_wtDate: "",
  past_headDate: "",
};

export const defaultDexaScans = [] as any[];

export const defaultLabs = {} as Record<string, { current: string; historical: string }>;

export const defaultClinical = {
  chiefComplaint: "",
  medHx: "",
  temples: "",
  clavicles: "",
  shoulders: "",
  scapula: "",
  interosseous: "",
  thighs: "",
  calves: "",
  orbital: "",
  cheek: "",
  tricepsFat: "",
  midAxillary: "",
  hair: [] as string[],
  eyes: [] as string[],
  mouthLips: [] as string[],
  tongue: [] as string[],
  teethGums: [] as string[],
  headNeck: [] as string[],
  nails: [] as string[],
  skin: [] as string[],
  pittingEdema: "",
  ascites: "",
  edemaDescription: "",
  temp: "",
  hr: "",
  spo2: "",
  bp: "",
  rr: "",
  gripStrength: "",
  giDistress: "",
  chewing: "",
  oralHygiene: "",
  swallowing: "",
  clinicalNotes: "",
};

export const defaultDietary = {
  recall: [{ label: "Meal 1", value: "" }],
  macroAdequacy: "",
  mealPatterns: "",
  currentDiets: "",
  fluidIntake: "",
  eatingEnv: "",
  culturalReligious: "",
  socialDynamics: "",
  dietOrder: "Standard Diet, Regular",
  actualIntake: "",
  oralCalories: "",
  oralProtein: "",
  oralWater: "",
  drugInteractions: "",
  otcMeds: "",
  herbalCAM: "",
  supplements: "",
  understanding: "",
  readiness: "5",
  psychTies: "",
  mealPrep: "",
  eatingOut: "",
  bingePurge: "",
  foodSecurity: "",
  foodSupplies: "",
  transport: "",
  physicalLevel: "",
  adls: "",
  feedingTasks: "",
  perception: "",
  qolGoals: "",
};
